"""price

Revision ID: 722257bf010f
Revises: f0d9042d48eb
Create Date: 2022-12-14 09:12:50.297305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722257bf010f'
down_revision = 'f0d9042d48eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
